const $=id=>document.getElementById(id),pick=a=>a[Math.floor(Math.random()*a.length)],rand=(a,b)=>Math.floor(Math.random()*(b-a+1))+a,clamp=n=>Math.max(1,Math.min(100,Math.round(n)));
const LABEL={strength:"Força",durability:"Durabilidade",speed:"Velocidade",intelligence:"Inteligência",combat:"Combate",power:"Poder",potential:"Potencial",luck:"Sorte"};
const rounds=[
["race","QUAL SUA RAÇA?","A origem do personagem."],["title","QUAL SEU TÍTULO?","O papel que ele ocupa."],["age","QUAL SUA IDADE?","A idade também altera a ficha."],["scale","FORÇA E DURABILIDADE?","O nível físico bruto."],["speed","QUAL SUA VELOCIDADE?","Da humana ao além do tempo."],["intelligence","QUAL SUA INTELIGÊNCIA?","Do comum ao quase onisciente."],["combat","QUAL SEU NÍVEL DE COMBATE?","Técnica e experiência."],["hasPower","POSSUI PODERES?","Se SIM, a próxima roleta escolhe o poder."],["power","QUAL SEU PODER?","Biblioteca de poderes + geração procedural."],["weapon","QUAL SUA ARMA?","De nenhuma arma a artefatos absurdos."],["luck","QUAL SUA SORTE?","O acaso também entra na ficha."],["weakness","QUAL SUA FRAQUEZA?","Todo personagem pode ter um preço."],["potential","QUAL SEU POTENCIAL?","O limite de crescimento."]];
const DB={race:LIB.races,title:LIB.titles,age:LIB.ages,scale:LIB.scales,speed:LIB.speeds,intelligence:LIB.intelligences,combat:LIB.combats,power:LIB.powers,weapon:LIB.weapons,luck:LIB.luck,weakness:LIB.weaknesses,potential:LIB.potentials,hasPower:[["Não","Sem poderes",{}],["Sim","Possui poderes",{potential:8}]]};
let state=null;
function fresh(){return{index:0,picks:[],stats:{strength:rand(15,55),durability:rand(15,55),speed:rand(15,55),intelligence:rand(15,55),combat:rand(5,55),power:0,potential:rand(20,70),luck:rand(1,100)},spinning:false};}
function active(){return rounds.filter(r=>r[0]!=="power"||state.picks.some(x=>x.key==="hasPower"&&x.name==="Sim"))}
function init(){state=fresh();renderGame();}
function renderGame(){const rs=active(),r=rs[state.index];$("app").innerHTML=`<div class="wrap"><div class="top"><span>CHARACTER // ROULETTE</span><span class="pill">V4.0</span></div><div class="hero"><h1>Crie um personagem impossível.</h1><div class="muted">Biblioteca modular + geração procedural. Uma roleta por vez.</div></div><section class="card"><div class="eyebrow">CONSTRUÇÃO • ${state.index+1}/${rs.length}</div><div class="bar"><i style="width:${state.index/rs.length*100}%"></i></div><div class="stage"><h2>${r[1]}</h2><div class="muted">${r[2]}</div><div class="roulette" id="roulette"><div class="pointer">▼</div><div class="value" id="value">?</div><div class="sub" id="sub">TOQUE PARA GIRAR</div></div><button class="btn" id="spin">🎰 GIRAR</button><button class="btn secondary hidden" id="next"></button><div class="effect hidden" id="effect"></div></div><div class="tabs">${rs.map((_,i)=>`<div class="tab ${i<=state.index?"done":""}">${i+1}</div>`).join("")}</div></section></div>`;$("spin").onclick=spin}
function spin(){if(state.spinning)return;state.spinning=true;$("spin").disabled=true;const key=active()[state.index][0],opts=DB[key];let i=0,n=rand(22,34);const timer=setInterval(()=>{$("value").textContent=pick(opts)[0];if(++i>=n){clearInterval(timer);commit(key)}} ,48)}
function commit(key){const item=pick(DB[key]),mods=item[2]||{};state.picks.push({key,name:item[0],tag:item[1],mods});for(const [k,v] of Object.entries(mods)){if(k in state.stats)state.stats[k]+=v}for(const k in state.stats)state.stats[k]=clamp(state.stats[k]);$("roulette").classList.remove("spinning");$("value").textContent=item[0];$("sub").textContent=item[1];$("effect").innerHTML="<b>EFEITOS NA FICHA</b><div class='chips'>"+(Object.entries(mods).length?Object.entries(mods).map(([k,v])=>`<span class='chip'>${LABEL[k]||k} ${v>0?"+":""}${v}</span>`).join(""):"<span class='chip'>Nenhum modificador direto</span>")+"</div>";$("effect").classList.remove("hidden");$("spin").classList.add("hidden");const b=$("next");b.classList.remove("hidden");b.textContent=state.index===active().length-1?"👤 FINALIZAR PERSONAGEM":"PRÓXIMA ROLAGEM →";b.onclick=next;state.spinning=false}
function next(){if(state.index>=active().length-1){finish();return}state.index++;renderGame();scrollTo({top:0,behavior:"smooth"})}
function get(k){return state.picks.find(x=>x.key===k)?.name||"desconhecido"}
function finish(){const c=state;const names=c.picks.map(x=>x.name);const sy=[];const boost=(name,mods)=>{if(names.includes(name)){for(const[k,v]of Object.entries(mods))c.stats[k]=clamp(c.stats[k]+v);sy.push(name)}};
if(names.includes("Deus")&&names.includes("Manipulação da realidade")){c.stats.power=clamp(c.stats.power+10);c.stats.potential=clamp(c.stats.potential+10);sy.push("Deus + Realidade")}
if(names.includes("Mestre lendário")&&names.includes("Katana")){c.stats.combat=clamp(c.stats.combat+8);sy.push("Mestre lendário + Katana")}
if(names.includes("Vampiro")&&names.includes("Imortalidade")){c.stats.power=clamp(c.stats.power+8);c.stats.potential=clamp(c.stats.potential+8);sy.push("Vampiro + Imortalidade")}
if(names.includes("Sorte impossível")){c.stats.potential=clamp(c.stats.potential+5);sy.push("Sorte impossível")}
c.synergies=sy;c.score=clamp(Object.values(c.stats).reduce((a,b)=>a+b,0)/8);c.name=pick(["Auren","Kael","Ren","Nox","Soren","Riven","Orion","Kairo","Aster","Nyra","Lys","Darian","Eryx","Veyra"])+" "+pick(["Valen","Voss","Drake","Ardent","Noctis","Raven","Solari","Kane","Astra","Veyne","Kuro","Zenith"]);
c.rarity=c.score>=96?"★★★★★ TRANSCENDENTE":c.score>=90?"★★★★★ LENDÁRIO":c.score>=78?"★★★★☆ ÉPICO":c.score>=62?"★★★☆☆ RARO":c.score>=45?"★★☆☆☆ INCOMUM":"★☆☆☆☆ COMUM";
const subtitle=`${get("race")} • ${get("title")} • ${get("age")}`;
const rows=c.picks.map(x=>`<div class="row"><span>${rounds.find(r=>r[0]===x.key)[1]}</span><b>${x.name}</b></div>`).join("");
$("app").innerHTML=`<div class="wrap"><div class="top"><span>CHARACTER // ROULETTE</span><span class="pill">RESULTADO</span></div><div class="hero"><div class="name">${c.name}</div><div class="cyan">${subtitle}</div><div class="rarity">${c.rarity} • Índice ${c.score}/100</div><div class="chips">${c.picks.map(x=>`<span class="chip">${x.name}</span>`).join("")}</div></div><div class="card"><div class="eyebrow">ATRIBUTOS FINAIS</div><div class="grid">${Object.entries(c.stats).map(([k,v])=>`<div class="stat"><div class="statline"><span>${LABEL[k]}</span><b>${v}</b></div><div class="fill"><i style="width:${v}%"></i></div></div>`).join("")}</div></div><div class="card"><div class="eyebrow">RESULTADOS</div><div class="rows">${rows}</div></div><div class="card"><div class="eyebrow">SINERGIAS</div><div class="text">${c.synergies.length?c.synergies.map(x=>`✦ ${x}`).join("<br>"):"Nenhuma sinergia especial."}</div></div><div class="card"><div class="eyebrow">HISTÓRIA</div><div class="text">${makeStory(c)}</div></div><div class="card actions"><button class="btn" id="save">💾 SALVAR</button><button class="btn secondary" id="share">↗ COMPARTILHAR</button></div><div class="card"><button class="btn" id="again">🎰 CRIAR OUTRO</button></div><div class="card"><div class="eyebrow">PERSONAGENS SALVOS</div><div id="saved"></div></div></div>`;
$("again").onclick=init;$("save").onclick=save;$("share").onclick=share;renderSaved()}
function makeStory(c){const best=Object.entries(c.stats).sort((a,b)=>b[1]-a[1])[0],worst=Object.entries(c.stats).sort((a,b)=>a[1]-b[1])[0];const power=get("hasPower")==="Sim"?`despertou ${get("power").toLowerCase()}`:"viveu sem poderes";return `${c.name} nasceu como ${get("race").toLowerCase()} e recebeu o título de ${get("title").toLowerCase()}. Aos ${get("age").toLowerCase()}, apresentava ${get("scale").toLowerCase()} de força e durabilidade, ${get("speed").toLowerCase()} de velocidade, inteligência ${get("intelligence").toLowerCase()} e combate ${get("combat").toLowerCase()}. Em algum ponto de sua vida, ${power}. Sua arma foi ${get("weapon").toLowerCase()} e sua sorte foi classificada como ${get("luck").toLowerCase()}. A maior limitação foi ${get("weakness").toLowerCase()}, enquanto seu potencial era ${get("potential").toLowerCase()}. O resultado final deixou ${LABEL[best[0]].toLowerCase()} como seu maior atributo (${best[1]}/100) e ${LABEL[worst[0]].toLowerCase()} como sua maior vulnerabilidade (${worst[1]}/100).`}
function save(){const a=JSON.parse(localStorage.getItem("crv4")||"[]");a.unshift(state);localStorage.setItem("crv4",JSON.stringify(a.slice(0,50)));alert("Personagem salvo!");renderSaved()}
function renderSaved(){const el=$("saved");if(!el)return;const a=JSON.parse(localStorage.getItem("crv4")||"[]");el.innerHTML=a.length?a.map((c,i)=>`<div class="saved"><b>${c.name}</b><small>${c.rarity} • ${c.score}/100</small></div>`).join(""):"<span class='muted'>Nenhum salvo ainda.</span>"}
async function share(){const text=`${state.name} — ${state.rarity} — ${state.score}/100`;try{if(navigator.share)await navigator.share({title:"Character Roulette",text});else{await navigator.clipboard.writeText(text);alert("Ficha copiada!")}}catch(e){}}
init();