const $=s=>document.querySelector(s), pick=a=>a[Math.floor(Math.random()*a.length)];
const STEPS=[['race','Qual sua raça?','races'],['title','Qual seu título?','titles'],['age','Idade?','ages'],['physical','Força e durabilidade?','physical'],['speed','Velocidade?','speed'],['intelligence','Inteligência?','intelligence'],['combat','Combate?','combat'],['hasPower','Possui poderes?','hasPower'],['power','Qual poder?','powers'],['weapon','Arma?','weapons'],['luck','Sorte?','luck'],['weakness','Fraqueza?','weakness'],['potential','Potencial?','potential']];
let state={step:0,picks:[],hasPower:false,rotation:0};
const esc=x=>String(x).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function steps(){return state.hasPower?STEPS:STEPS.filter(x=>x[0]!=='power')}
function vals(key){return LIBRARY[key]||[]}
function render(){const ss=steps(),s=ss[state.step],list=vals(s[2]);const n=list.length;const bg=`conic-gradient(from 0deg,${Array.from({length:n},(_,i)=>`${i%2?'#101010':'#161616'} ${i*100/n}% ${(i+1)*100/n}%`).join(',')})`;
$('#app').innerHTML=`<main class="wrap"><header><b>CHARACTER // ROULETTE</b><span class="version">V5</span></header><section class="intro"><div class="eyebrow">GERADOR DE PERSONAGEM</div><h1>Uma roleta.<br>Um personagem.</h1><p>Um atributo por giro. Todas as opções têm a mesma chance.</p></section><section class="panel"><div class="counter">${state.step+1} / ${ss.length}</div><h2 class="question">${s[1]}</h2><p class="hint">Escolha definida pelo ponteiro.</p><div class="wheelbox"><div class="pointer"></div><div id="wheel" class="wheel" style="background:${bg}">${list.map((v,i)=>{const a=(i+.5)*360/n;return `<span class="label" style="transform:rotate(${a}deg) translateY(-${Math.min(40,n>35?36:48)}vw) rotate(${-a}deg)">${esc(v)}</span>`}).join('')}</div></div><div class="wheelmeta">GIRO REAL · ${n} OPÇÕES</div><button id="spin" class="btn">GIRAR</button><div id="result" class="result" hidden></div></section></main>`;
$('#spin').onclick=spin}
function spin(){const ss=steps(),s=ss[state.step],list=vals(s[2]),n=list.length;const idx=Math.floor(Math.random()*n),step=360/n,center=idx*step+step/2;const turns=5+Math.floor(Math.random()*3);const desired=360-center;state.rotation+=turns*360+desired-(state.rotation%360);const w=$('#wheel'),b=$('#spin'),r=$('#result');b.disabled=true;w.style.transform=`rotate(${state.rotation}deg)`;setTimeout(()=>{const value=list[idx];state.picks.push({key:s[0],label:s[1],value});if(s[0]==='hasPower')state.hasPower=value==='Sim';r.hidden=false;r.innerHTML=`<b>${esc(value)}</b><small>resultado registrado</small>`;b.textContent=state.step===steps().length-1?'VER PERSONAGEM':'PRÓXIMO GIRO';b.disabled=false;b.onclick=next},4600)}
function next(){if(state.step>=steps().length-1){finish();return}state.step++;render()}
function num(v,key){const a=vals(key),i=a.indexOf(v);return i<0?50:Math.round(5+i*95/(a.length-1))}
function finish(){const m=Object.fromEntries(state.picks.map(x=>[x.key,x.value]));const stats={"Força":num(m.physical,'physical'),"Durabilidade":num(m.physical,'physical'),"Velocidade":num(m.speed,'speed'),"Inteligência":num(m.intelligence,'intelligence'),"Combate":num(m.combat,'combat'),"Poder":m.power?num(m.power,'powers'):0,"Potencial":num(m.potential,'potential'),"Sorte":num(m.luck,'luck')};let score=Math.round(Object.values(stats).reduce((a,b)=>a+b,0)/8);let r=Math.min(7,Math.floor(score/13));if(m.power&&/realidade|causalidade|existência|conceitos|onipotência|onipresença|onisciência/i.test(m.power))r=Math.max(r,6);const colors=['#aaa','#8bd17c','#7aa7ff','#b28cff','#ffd45c','#ff7a7a','#ff5ad9','#8dfcff'];const names=['COMUM','INCOMUM','RARO','ÉPICO','LENDÁRIO','MÍTICO','DIVINO','TRANSCENDENTE'];const c=colors[r],stars='★'.repeat(r+1);const name=pick(['Kael','Ren','Sora','Nox','Aren','Kairo','Orion','Aster','Riven','Noa'])+' '+pick(['Valen','Voss','Kane','Ardent','Zenith','Noctis','Solari','Raven']);const statHTML=Object.entries(stats).map(([k,v])=>`<div class="stat" style="color:${c}"><span>${k}</span><b>${v}</b><div class="bar"><i style="width:${v}%"></i></div></div>`).join('');const rows=state.picks.map(x=>`<div class="row"><span>${esc(x.label)}</span><b>${esc(x.value)}</b></div>`).join('');$('#app').innerHTML=`<main class="wrap"><header><b>CHARACTER // ROULETTE</b><span class="version">V5</span></header><section class="final"><div class="eyebrow">PERSONAGEM CONCLUÍDO</div><div class="stars" style="color:${c};text-shadow:0 0 ${5+r*5}px ${c}">${stars}</div><div style="color:${c};font-size:10px;letter-spacing:.2em">${names[r]}</div><h1 style="text-shadow:0 0 ${r*3}px ${c}">${esc(name)}</h1><div class="sub">${esc(m.race)} · ${esc(m.title)} · ${esc(m.age)}</div><div class="score" style="color:${c}">${score}/100</div></section><section class="card"><h2>ESTATÍSTICAS</h2><div class="stats">${statHTML}</div></section><section class="card"><h2>FICHA SORTEADA</h2>${rows}</section><section class="card"><h2>HISTÓRIA</h2><p class="story">${esc(name)} nasceu como ${esc(m.race).toLowerCase()} e recebeu o título de ${esc(m.title).toLowerCase()}. Aos ${esc(m.age)}, possuía ${esc(m.physical).toLowerCase()}, ${esc(m.speed).toLowerCase()} velocidade, ${esc(m.intelligence).toLowerCase()} inteligência e ${esc(m.combat).toLowerCase()} domínio de combate. ${m.power?`Seu poder era ${esc(m.power).toLowerCase()}.`:'Não possuía poderes.'} Portava ${esc(m.weapon).toLowerCase()} e carregava ${esc(m.weakness).toLowerCase()} como fraqueza. Seu potencial era ${esc(m.potential).toLowerCase()}. A partir daqui, a vida desse personagem pode ir para qualquer direção.</p></section><button id="again" class="btn again">CRIAR OUTRO</button></main>`;$('#again').onclick=()=>{state={step:0,picks:[],hasPower:false,rotation:0};render()}}
render();
