/* ROULETA DA VIDA V21 — CHARACTER FORGE */
(()=>{
'use strict';
const clamp=(n,a,b)=>Math.max(a,Math.min(b,n));
function randomInt(max){if(max<=1)return 0;const c=globalThis.crypto;if(c?.getRandomValues){const a=new Uint32Array(1),lim=Math.floor(0x100000000/max)*max;do{c.getRandomValues(a)}while(a[0]>=lim);return a[0]%max;}return Math.floor(Math.random()*max)}
const norm=x=>Array.isArray(x)?{name:String(x[0]),value:Number(x[1]??50),ref:String(x[2]??''),refType:'referência',refWhy:String(x[2]??'')}:({...x});
const pick=a=>norm(a[randomInt(a.length)]);
const draw=k=>{const a=window.LIBRARY?.[k]||[];return a.length?pick(a):{name:'Resultado desconhecido',value:50,refType:'fallback',refWhy:'banco vazio',tags:'unknown'}};
const firstNames=['Akira','Aiko','Ren','Rin','Haru','Yuki','Sora','Kai','Ryu','Mei','Lena','Nora','Elian','Lucian','Mira','Viktor','Iris','Dante','Valen','Arthur','Evelyn','Milo','Theo','Adrian','Naomi','Levi','Amara','Soren','Freya','Nikolai','Zara','Samir','Layla','Kenji','Emi','Hugo','Clara','Rafael','Luna','Mika','Noah','Aya','Kaito','Selene','Leon','Yuna','Cassian','Maya'];
const lastNames=['Aoki','Kurosawa','Hayashi','Mori','Takeda','Arakawa','Silva','Costa','Moreau','Dubois','Blackwood','Ashford','Ravenwood','Vale','Everett','Cruz','Navarro','Volkov','Kovacs','Hale','Sterling','Nightingale','Frost','Grimm','Stone','Reyes','Sato','Khan','Ishikawa','Mercer','Laurent','Bianchi','Hawthorne','Bellamy','Sinclair','Marceau','Orlov'];
const name=()=>firstNames[randomInt(firstNames.length)]+' '+lastNames[randomInt(lastNames.length)];
const yesPower=()=>randomInt(100)<68;
const score=x=>Number.isFinite(Number(x?.value))?Number(x.value):50;
const tags=x=>String(x?.tags||'').split(',').map(s=>s.trim()).filter(Boolean);
const tier=v=>v<20?0:v<35?1:v<50?2:v<65?3:v<78?4:v<88?5:v<94?6:v<98?7:8;
const rarityNames=[['Comum',1,'#9aa0aa'],['Incomum',2,'#63df92'],['Raro',3,'#59adff'],['Épico',4,'#9d70ff'],['Lendário',5,'#ff67d3'],['Mítico',6,'#ffad45'],['Divino',7,'#ffe75d'],['Transcendente',8,'#63eaff'],['Absoluto',9,'#fff']];
function countSynergy(p){const sets=Object.values(p||{}).map(x=>new Set(tags(x)));const has=(a,b)=>sets.some(s=>s.has(a))&&sets.some(s=>s.has(b));let n=0;if(has('speedster','lightning'))n++;if(has('dragon','fire'))n++;if(has('psychic','mind'))n++;if(has('sword','katana'))n++;if(has('cosmic','energy'))n++;if(has('tech','armor'))n++;if(has('wing','light'))n++;if(has('demon','dark'))n++;if(has('martial','muscle'))n++;if(has('science','tech'))n++;return n}
function rarity(p){const keys=['race','title','appearance','age','condition','force','speed','intelligence','combat','talent','potential','weapons','life'];if(p.hasPower?.name==='Sim')keys.push('power','control');const ts=keys.map(k=>tier(score(p[k]))),high=ts.filter(x=>x>=5).length,extreme=ts.filter(x=>x>=7).length,absolute=ts.filter(x=>x>=8).length,breadth=ts.filter(x=>x>=4).length,weak=ts.filter(x=>x<=1).length,synergies=countSynergy(p);let stars=1;if(breadth>=2||Math.max(...ts)>=2)stars=2;if(breadth>=4||high>=1)stars=3;if(breadth>=5&&high>=2)stars=4;if(breadth>=6&&high>=3)stars=5;if((breadth>=7&&high>=3)||extreme>=1||synergies>=2)stars=6;if((breadth>=8&&extreme>=2)||absolute>=1||synergies>=3)stars=7;if((breadth>=9&&extreme>=3)||(absolute>=2&&high>=5)||synergies>=4)stars=8;if((breadth>=11&&extreme>=4&&weak<=1)||(absolute>=3&&synergies>=4&&weak===0))stars=9;if(p.hasPower?.name!=='Sim')stars=Math.min(stars,8);const r=rarityNames[stars-1];return{name:r[0],stars,color:r[2],high,extreme,absolute,breadth,synergies}}
function personality(){const pool=[['observador','conhecimento','orgulho','entender o mundo','perder o controle'],['curioso','liberdade','impaciência','descobrir algo impossível','ficar preso ao passado'],['determinado','proteção','teimosia','provar seu valor','falhar com alguém'],['calculista','verdade','desconfiança','encontrar a resposta definitiva','ser enganado'],['melancólico','independência','isolamento','construir uma vida própria','ficar sozinho'],['ambicioso','poder','orgulho','alcançar o topo','ser esquecido'],['compassivo','justiça','medo de ferir outros','proteger quem ama','não conseguir salvar alguém'],['imprevisível','liberdade','impulsividade','viver algo que ninguém viveu','uma vida sem sentido']];const a=pool[randomInt(pool.length)];return{trait:a[0],ideal:a[1],flaw:a[2],goal:a[3],fear:a[4]}}
function reference(obj){if(!obj)return null;return{name:obj.name||'—',type:obj.refType||'referência',why:obj.refWhy||obj.ref||'sem descrição',value:score(obj),tags:tags(obj)}}
function complete(p){const out={...(p||{})};const map={race:'races',title:'titles',appearance:'appearance',age:'age',condition:'condition',force:'force',speed:'speed',intelligence:'intelligence',combat:'combat',talent:'talent',potential:'potential',weapons:'weapons',life:'life'};for(const [k,db] of Object.entries(map))if(!out[k]?.name)out[k]=draw(db);if(!out.name?.name)out.name={name:name(),refType:'sistema de nomes',refWhy:'combinação procedural de nomes disponíveis'};if(!out.hasPower?.name)out.hasPower={name:yesPower()?'Sim':'Não',refType:'regra do sistema',refWhy:'chance independente de receber um poder'};if(out.hasPower.name==='Sim'){if(!out.power?.name)out.power=draw('power');if(!out.control?.name)out.control=draw('control')}else{out.power={name:'Nenhum poder',refType:'estado',refWhy:'sem poder sobrenatural',value:0,tags:'none'};out.control={name:'Sem domínio',refType:'estado',refWhy:'não há poder para dominar',value:0,tags:'none'}}return out}
function compose(p){const q=complete(p),refs={};for(const k of Object.keys(q))if(k!=='hasPower')refs[k]=reference(q[k]);const visualSeed=[q.name?.name,...Object.keys(q).map(k=>q[k]?.name||'')].join('|');const rar=rarity(q);return{p:q,rarity:rar,personality:personality(q),refs,visualSeed,synergies:rar.synergies}}
function forge(){return compose({})}
window.RV={VERSION:'21.0.0',randomInt,pick,draw,name,yesPower,score,tier,rarity,compose,forge,reference,tags};
})();
