/* Biblioteca-base. Cada item possui peso 1.
   Os grandes catálogos são carregados pelo library-loader.js.
*/
const LIBRARY = {
  races: ["Humano","Humano aprimorado","Saiyajin","Kryptoniano","Asgardiano","Mutante","Ciborgue","Android","Alienígena","Elfo","Anão","Orc","Oni","Yokai","Kitsune","Vampiro","Lobisomem","Demônio","Anjo","Serafim","Dragão","Fada","Gigante","Titã","Semideus","Deus","Espírito","Fantasma","Elemental","Golem","Construto","Múmia","Djinn","Sereia","Centauro","Híbrido","Metamorfo","Parasita","Simbionte","Entidade cósmica","Entidade conceitual","Ser primordial","Ser extradimensional","Avatar","Existência abstrata","Consciência coletiva","Inteligência artificial","Raça desconhecida"],
  titles: ["Pessoa comum","Estudante","Atleta","Soldado","Mercenário","Caçador","Assassino","Ladrão","Detetive","Cientista","Inventor","Médico","Professor","Artista","Espadachim","Arqueiro","Mestre de artes marciais","Mago","Feiticeiro","Alquimista","Nobre","Príncipe","Princesa","Rei","Rainha","Imperador","Imperatriz","General","Comandante","Capitão","Herói","Vilão","Anti-herói","Guardião","Campeão","Escolhido","Profeta","Oráculo","Lorde Demônio","Rei Demônio","Deus-Rei","Soberano Cósmico","Arauto","Avatar","Executor","Forasteiro","Reencarnação","Anomalia","Desconhecido"],
  ages: ["3 anos","7 anos","10 anos","13 anos","15 anos","16 anos","17 anos","18 anos","21 anos","25 anos","30 anos","40 anos","50 anos","65 anos","80 anos","100 anos","250 anos","500 anos","1.000 anos","5.000 anos","10.000 anos","100.000 anos","1 milhão de anos","Anterior à história registrada","Sem idade mensurável"],
  physical: ["Extremamente fraco","Fraco","Humano comum","Humano atlético","Humano excepcional","Sobre-humano","Super-humano","Monstruoso","Colossal","Titânico","Destruidor de estruturas","Destruidor de cidades","Destruidor de países","Continental","Planetário","Estelar","Sistema estelar","Galáctico","Universal","Multiversal","Transcendente","Sem escala mensurável"],
  speed: ["Imóvel","Muito lento","Humano comum","Atlético","Humano excepcional","Supersônico","Hipersônico","Mach extremo","Relativístico","Próximo da luz","Velocidade da luz","Mais rápido que a luz","Instantâneo","Além do espaço","Além do tempo","Sem velocidade mensurável"],
  intelligence: ["Extremamente limitada","Baixa","Comum","Acima da média","Inteligente","Muito inteligente","Gênio","Supergênio","Intelecto extraordinário","Mente estratégica excepcional","Consciência sobre-humana","Consciência cósmica","Quase onisciente","Onisciente","Além do conceito de inteligência"],
  combat: ["Sem treinamento","Inexperiente","Amador","Treinado","Competente","Profissional","Especialista","Elite","Mestre","Mestre absoluto","Mestre lendário","Combatente sobrenatural","Guerreiro divino","Perfeito","Além da técnica"],
  powers: ["Superforça","Supervelocidade","Regeneração","Voo","Telepatia","Telecinese","Controle mental","Ilusão","Precognição","Pirocinese","Criocinese","Eletrocinese","Aerocinese","Hidrocinese","Geocinese","Fotocinese","Umbracinese","Manipulação de sangue","Manipulação de almas","Necromancia","Invocação","Teletransporte","Portais dimensionais","Intangibilidade","Manipulação gravitacional","Manipulação espacial","Manipulação temporal","Parar o tempo","Voltar no tempo","Acelerar o tempo","Manipulação da matéria","Transmutação","Manipulação de energia","Absorção de energia","Drenagem de energia","Cópia de habilidades","Roubo de habilidades","Adaptação","Evolução instantânea","Imortalidade","Ressurreição","Regeneração conceitual","Manipulação da realidade","Manipulação da causalidade","Manipulação da probabilidade","Manipulação do destino","Manipulação da vida","Manipulação da morte","Manipulação de conceitos","Apagar existência","Reescrever leis da realidade","Criar universos","Destruir universos","Existência abstrata","Onisciência","Onipresença","Onipotência"],
  weapons: ["Nenhuma","Faca","Adaga","Espada","Katana","Espada dupla","Lança","Arco","Besta","Machado","Martelo","Foice","Chicote","Correntes","Armas de fogo","Arma de energia","Arma tecnológica","Arma viva","Arma amaldiçoada","Arma mágica","Artefato antigo","Relíquia lendária","Arma divina","Arma cósmica","Arma dimensional","Arma conceitual","Arma senciente","Arma capaz de destruir mundos"],
  luck: ["Maldição absoluta","Azar extremo","Muito azar","Azar","Abaixo da média","Normal","Acima da média","Sortudo","Muito sortudo","Extremamente sortudo","Abençoado pelo destino","Sorte impossível","Probabilidade quebrada"],
  weakness: ["Nenhuma fraqueza conhecida","Corpo frágil","Baixa resistência","Velocidade limitada","Intelecto limitado","Pouco treinamento","Poder instável","Poder consome energia","Fraqueza elemental","Fraqueza mental","Fraqueza emocional","Fraqueza física específica","Arma necessária","Precisa de concentração","Tempo de recarga","Preço sobrenatural","Pode ser morto","Mortalidade","Uma fraqueza desconhecida"],
  potential: ["Nenhum potencial","Muito baixo","Baixo","Moderado","Normal","Acima da média","Alto","Muito alto","Prodígio","Monstruoso","Absurdo","Divino","Transcendente","Potencial ilimitado","Sem teto conhecido"]
};