/* Biblioteca local V5 — todas as entradas da mesma categoria têm a mesma chance. */
const LIBRARY={
 races:["Humano","Elfo","Elfo Negro","Anão","Orc","Goblin","Troll","Ogro","Gigante","Fada","Draconiano","Dragão","Vampiro","Lobisomem","Demônio","Anjo","Semi-Deus","Deus","Espírito","Fantasma","Yokai","Kitsune","Oni","Shinigami","Homúnculo","Ciborgue","Android","Alienígena","Mutante","Metamorfo","Elemental","Golem","Serafim","Titã","Entidade Cósmica","Entidade Abstrata","Parasita","Monstro","Bestial","Híbrido"],
 titles:["Ninguém","Camponês","Viajante","Mercenário","Caçador","Aventureiro","Guarda","Soldado","Cavaleiro","Assassino","Ladrão","Mago","Alquimista","Curandeiro","Monge","Capitão","General","Comandante","Rei","Rainha","Príncipe","Imperador","Imperatriz","Herói","Anti-Herói","Vilão","Lorde Demônio","Soberano","Campeão","Profeta","Oráculo","Guardião","Executor","Arauto","Mestre","Lenda","Reencarnado","Escolhido","Avatar","Deus Vivo"],
 ages:["6 anos","10 anos","13 anos","16 anos","18 anos","21 anos","25 anos","30 anos","40 anos","50 anos","65 anos","80 anos","100 anos","150 anos","300 anos","500 anos","1.000 anos","10.000 anos","Imortal — aparência jovem","Imortal — aparência adulta"],
 physical:["Frágil","Muito fraco","Fraco","Abaixo da média","Humano comum","Atlético","Forte","Muito forte","Sobre-humano","Monstruoso","Colossal","Titânico","Divino","Cósmico","Infinito"],
 speed:["Parado","Muito lento","Lento","Normal","Atlético","Muito rápido","Supersônico","Hipersonico","Relâmpago","Luz","Mais rápido que a luz","Instantâneo","Teleporte curto","Teleporte ilimitado","Velocidade conceitual"],
 intelligence:["Instintivo","Muito limitado","Baixo","Normal","Esperto","Inteligente","Gênio","Supergênio","Mente estratégica","Intelecto monstruoso","Intelecto sobre-humano","Onisciente parcial","Onisciente","Além da lógica","Consciência absoluta"],
 combat:["Nunca lutou","Inexperiente","Amador","Briga de rua","Treinado","Veterano","Especialista","Mestre marcial","Mestre de armas","Assassino nato","Lenda do combate","Mestre absoluto","Predador perfeito","Guerreiro divino","Combatente transcendental"],
 hasPower:["Não","Sim"],
 powers:["Nenhum","Superforça","Supervelocidade","Regeneração","Voo","Telecinese","Telepatia","Precognição","Clonagem","Invisibilidade","Intangibilidade","Manipulação de fogo","Manipulação de água","Manipulação de gelo","Manipulação de vento","Manipulação de terra","Manipulação de eletricidade","Manipulação de luz","Manipulação de sombras","Gravidade","Magnetismo","Barreiras de energia","Absorção de energia","Roubo de poderes","Cópia de poderes","Cancelamento de poderes","Controle de sangue","Controle de plantas","Transformação","Metamorfose","Invocação","Necromancia","Ilusão absoluta","Controle mental","Manipulação espacial","Manipulação temporal","Viagem no tempo","Parada do tempo","Manipulação da realidade","Manipulação da causalidade","Manipulação da alma","Manipulação da existência","Manipulação de conceitos","Criação de matéria","Destruição absoluta","Onipotência limitada","Onisciência","Onipresença","Apagamento existencial","Poder além dos conceitos"],
 weapons:["Nenhuma","Punhos","Adagas","Espada curta","Katana","Espada longa","Duas espadas","Espada colossal","Lança","Tridente","Machado","Machado colossal","Martelo","Arco","Arco mágico","Besta","Arma de fogo","Rifle","Pistolas duplas","Canhão","Cajado","Grimório","Foice","Foice da alma","Corrente","Chicote","Arma viva","Arma amaldiçoada","Arma divina","Arma cósmica","Arma que manipula a realidade"],
 luck:["Maldição de azar","Muito azarado","Azarado","Abaixo da média","Normal","Sortudo","Muito sortudo","Absurdo","Milagre ambulante","Favorito do destino"],
 weakness:["Nenhuma aparente","Baixa resistência","Medo","Orgulho","Raiva","Ingenuidade","Curiosidade","Fome","Sede de poder","Fragilidade física","Fragilidade mental","Poder instável","Depende da arma","Depende de aliados","Uma fraqueza desconhecida"],
 potential:["Sem potencial","Baixo","Limitado","Comum","Acima da média","Grande","Excepcional","Monstruoso","Lendário","Divino","Transcendental","Sem limite conhecido","Potencial para superar deuses"]
};
